# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8048a9fca11408bb8c671cb5b7f5bd5fc625bcbc117c90d79ac19144f7b2aac7ba6e866d63ce4b70ba66c0becb7d7bc89634ae026ee3665e884a9a76e9d89e

test:
  secret_key_base: 9162cd98a5ea2c05b7d2cb31185acf409d9a1c66908fe1d9a1598636b4bd28b4bfecd8a869b2c49e308d81889e780447c016c333a83be4372e2501948a340291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
